### ISSUE TITLE
Problem executing publish command

### ISSUE THREAD

**Issue by denisonl84** [DarkGhostHunter/Transbanker#11]
Hi.
I'm getting trouble while executing php artisan vendor:publish --provider="DarkGhostHunter\Transbanker\TransbankerServiceProvider" . It throws this : Unable to locate publishable resources.
Can you support me, please? What can I do to fix this?

Thanks a lot.

**Comment by denisonl84** [comment]
I think this is the solution: php artisan vendor:publish --provider="DarkGhostHunter\Transbanker\ServiceProvider"... I deleted the word Transbanker from "TransbankerServiceProvider"; It worked for me.

**Comment by denisonl84** [comment]
Sorry, It doesn't work neither

**Comment by DarkGhostHunter** [comment]
Try again without the quotes.
